name: infinity_cached_scroll
description: .

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  http: ^0.13.0
  equatable: ^2.0.3
  stream_transform: ^2.0.0
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  logger: ^1.1.0
  json_serializable: ^6.2.0
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.1
  share_plus: ^4.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
